build:
	gcc -g oets.c -o oets -lpthread -lm -Wall
	gcc -g shear.c -o shear -lpthread -lm -Wall
	gcc -g merge.c -o merge -lpthread -lm -Wall
	gcc -g parallel_binary_search.c -o parallel_binary_search -lpthread -lm -Wall
clean:
	rm -rf oets shear merge parallel_binary_search
