CC=gcc
FLAGS= -Wall -Wextra

build:E1 E2 E3 E4

E1: E1.c
	$(CC) $(FLAGS) $(@).c -o $(@)

E2: E2.c
	$(CC) $(FLAGS) $(@).c -o $(@)

E3: E3.c
	$(CC) $(FLAGS) $(@).c -o $(@)

E4: E4.c
	$(CC) $(FLAGS) $(@).c -o $(@)
