#!/bin/sh
#
# SensorDriver        Starts Sensor Driver.
#


umask 077

start() {

        printf "Starting Sensor Driver: "
        /bin/sensor_service.py >> /var/log/sensor_service.log &
        echo "OK"
        # sleep 1
        # if [ $(ps |grep sensor_service.py | wc -l) = 2 ]
        # then
        # fi
}
stop() {
        printf "Stopping Sensor Driver: "
        killall sensor_service.py
        echo "OK"
}
restart() {
        stop
        start
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        restart
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
