#!/bin/sh
#
# SensorWebServer        Starts Sensor Web Server.
#


umask 077

start() {

        printf "Starting Sensor Web Server: "
        /opt/webserver/main.py &> /var/log/webserver.log &
        echo "OK"
        # sleep 1
        # if [ $(ps |grep sensor_service.py | wc -l) = 2 ]
        # then
        # fi
}
stop() {
        printf "Stopping Sensor Web Server: "
        killall main.py
        echo "OK"
}
restart() {
        stop
        start
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        restart
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
