apiVersion: 1

datasources:
  - name: influxdb
    type: influxdb
    isDefault: true
    access: proxy
    user: $DOCKER_INFLUXDB_INIT_USERNAME
    url: http://db:8086
    secureJsonData:
        token: $DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
    jsonData:
        version: Flux
        organization: $DOCKER_INFLUXDB_INIT_ORG
        defaultBucket: $DOCKER_INFLUXDB_INIT_BUCKET